name: Reusable Workflow

on:
  workflow_call:
    inputs:
      steps_to_run:
        required: true
        type: string

jobs:
  step-a:
    if: contains(inputs.steps_to_run, 'A')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job A"

  step-b:
    if: contains(inputs.steps_to_run, 'B')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job B"

  step-c:
    if: contains(inputs.steps_to_run, 'C')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job C"
