name: Main Caller Workflow

on:
  workflow_dispatch:

jobs:
  run-a:
    uses: ./.github/workflows/called.yml
    with:
      step_to_run: A

  run-b:
    needs: run-a
    uses: ./.github/workflows/called.yml
    with:
      step_to_run: B

  run-c:
    needs: run-b
    uses: ./.github/workflows/called.yml
    with:
      step_to_run: C
