name: Main Caller Workflow

on:
  workflow_dispatch:
    inputs:
      steps:
        description: 'Comma-separated steps to run (e.g., A,C,B)'
        required: true
        default: 'A,B,C'

jobs:
  run-ordered-steps:
    uses: ./.github/workflows/called.yml
    with:
      steps_to_run: ${{ github.event.inputs.steps }}
