name: Mixed inputs

on:
  workflow_dispatch:
    inputs:

      Build-version:
        required: true
      Build-number:
        required: true
      Upload-to-MADS:
        type: boolean
        description: Select if it requires to upload IPA in MADS
      environment:
        type: environment

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      API_TOKEN : '${{ secrets.API_TOKEN }}'
    steps:
    - name: Build information
      run: echo "Build version - ${{ github.event.inputs.Build-version }}, Build number - ${{ github.event.inputs.Build-number }} "
    - name : Accessing github settings variable
      run :  |
        echo "Environment Server URL: ${{ vars.ENV_SERVER_URL }}"
    - name : Accessing github secret variable
      run : |
        echo "API TOKEN from secrets: ${{ secrets.API_TOKEN }}"
        echo "APIToken: $API_TOKEN from environment"
    - name: If required to upload IPA in MADS
      if: ${{ github.event.inputs.Upload-to-MADS == 'true' }}
      run: echo "MADS upload required!"
