name: Mixed inputs

on:
  workflow_dispatch:
    inputs:

      Build-version:
        required: true
      Build-number:
        required: true
      Upload-to-MADS:
        type: boolean
        description: Select if it requires to upload IPA in MADS
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Build information
      run: echo "${{ github.event.inputs.Build-version }} ${{ github.event.inputs.Build-number }} "
    - name : Accessing github settings variable
      run :  |
        echo "Environment Server URL:"
        echo "${{ env.ENV_SERVER_URL }}"
    - name : Accessing github settings variable
      run : |
        echo "API TOKEN from secrets:"
        echo "${{ env.secrets.API_TOKEN }}"
    - name: Check and upload for MADS
      if: ${{ github.event.inputs.Upload-to-MADS == 'true' }}
      run: echo "MADS upload required!"
