name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      Build-version:
        required: true
      Build-number:
        required: true
      Upload-to-MADS:
        type: boolean
        description: Select if it requires to upload IPA in MADS
      environment:
        type: environment
jobs:
  Build:
    runs-on: macos-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      API_TOKEN : '${{ secrets.API_TOKEN }}'
    steps:
      - uses: actions/checkout@v3
      - name: replace-env-file-action
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env.${{ github.event.inputs.environment }}
      - name: setting the variables
        run: |
          echo "CUSTOM_VAR1='This is modified custom value'" >> $GITHUB_ENV
          echo "KEY2=VALUE2" >> $GITHUB_ENV
          echo "KEY3=VALUE3" >> $GITHUB_ENV
#         uses: qgxpagamentos/replace-env-file-action@v1
#         with:
#           path: ./.env.${{ github.event.inputs.environment }}
#           add_if_not_exist: true
#           map: |
#             CUSTOM_VAR1 = "This is modified custom value"
#             KEY2=VALUE2
      - name: Load .env file after modified
        uses: xom9ikk/dotenv@v2.2.0
        with:
          path: ./
          load-mode: strict
          mode: ${{ github.event.inputs.environment }}
      - name: Fetching custom values after modified
        run: |
          echo "Env file Custom Variable - $CUSTOM_VAR1"
          echo "Newly added var - $KEY2"
          echo "Newly added var - $KEY3"
      - name: Build information
        run: echo "Build version - ${{ github.event.inputs.Build-version }}, Build number - ${{ github.event.inputs.Build-number }} "
      - name : Accessing github settings variable
        run :  |
          echo "Environment Server URL: ${{ vars.ENV_SERVER_URL }}"
      - name : Accessing github secret variable
        run : |
          echo "API TOKEN from secrets: ${{ secrets.API_TOKEN }}"
          echo "APIToken: $API_TOKEN from environment"
      - name : Accessing github repository global variable
        run :  |
          echo "Repository Global variable: ${{ vars.GLOBAL_VAR }}"
      - name: If required to upload IPA in MADS
        if: ${{ github.event.inputs.Upload-to-MADS == 'true' }}
        run: echo "MADS upload required!"
