name: EnvConfig

on:
  workflow_dispatch:
env:
  env_name: ${{ github.event.inputs.environment }}
jobs:
  Build:
    runs-on: macos-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      API_TOKEN : '${{ secrets.API_TOKEN }}'
    steps:
      - name : Accessing env global variable
        run :  |
          echo "Environment name: ${{ env.env_name }}"
      - name : Accessing github secret variable
        run : |
          echo "API TOKEN from secrets: ${{ secrets.API_TOKEN }}"
          echo "APIToken: $API_TOKEN from environment"
      - name : Accessing github repository global variable
        run :  |
          echo "Repository Global variable: ${{ vars.GLOBAL_VAR }}"
      - name: If required to upload IPA in MADS
        if: ${{ github.event.inputs.Upload-to-MADS == 'true' }}
        run: echo "MADS upload required!"
