name: EnvConfig

on:
  workflow_dispatch:
    inputs:
     environment:
      type: environment
env:
  env_name: ${{ github.event.inputs.environment }}
jobs:
  Build:
    runs-on: macos-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      API_TOKEN : '${{ secrets.API_TOKEN }}'
    steps:
      - name : Accessing env global variable
        run :  |
          echo "Environment name: ${{ env.env_name }}"
      - name : Accessing github secret variable
        run : |
          echo "API TOKEN from secrets: ${{ secrets.API_TOKEN }}"
          echo "APIToken: $API_TOKEN from environment"
      - name : Accessing github repository global variable
        run :  |
          echo "Repository Global variable: ${{ vars.GLOBAL_VAR }}"
  Test1:
    needs: Build
    runs-on: macos-latest
    steps:
        - id: envString
          uses: ASzc/change-string-case-action@v5
          with:
            string: ${{ env.env_name }}
        - name: step2
          run : |
            echo "Environment name before lowercase: ${{ env.env_name }}"
            echo "Environment name after lowercase: ${{ steps.envString.outputs.lowercase }}"
  Test2:
    needs: Test1
    runs-on: macos-latest
    steps:
      - name: Fetch environment from another job
        run : |
          echo "Fetch environment from anther job : ${{ jobs.Test1.steps.envString.outputs }}"
    

