name: EnvConfig

on:
  workflow_dispatch:
    inputs:
     environment:
     type: environment
env:
  env_name: ${{ github.event.inputs.environment }}
jobs:
  Build:
    runs-on: macos-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      API_TOKEN : '${{ secrets.API_TOKEN }}'
    steps:
      - name : Accessing env global variable
        run :  |
          echo "Environment name: ${{ env.env_name }}"
      - name : Accessing github secret variable
        run : |
          echo "API TOKEN from secrets: ${{ secrets.API_TOKEN }}"
          echo "APIToken: $API_TOKEN from environment"
      - name : Accessing github repository global variable
        run :  |
          echo "Repository Global variable: ${{ vars.GLOBAL_VAR }}"
  Test:
    runs-on: macos-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name : String lower
        echo "Environment name: ${{ env.env_name }}"
      
    

